export const statusCode = {
	invalid: {
		INVALID_PARAMS: "INVALID_PARAMS",
		INVALID_TYPES: "INVALID_TYPES",
		INVALID_ROLE_TYPE: "INVALID_ROLE_TYPE",
		INVALID_CATEGORY_TYPE: "INVALID_CATEGORY_TYPE",
		INVALID_EMAIL: "INVALID_EMAIL",
		INVALID_TOKEN: "INVALID_TOKEN",
		INVALID_DATE: "INVALID_DATE",
		MAX_OR_MIN_NAME_LENGTH: "MAX_OR_MIN_NAME_LENGTH",
		MAX_OR_MIN_TITLE_LENGTH: "MAX_OR_MIN_TITLE_LENGTH",
		MAX_OR_MIN_NOTE_LENGTH: "MAX_OR_MIN_NOTE_LENGTH"
	},
	conflict: {
		USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
		CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
		NOT_FOUND_USER: "NOT_FOUND_USER",
		NOT_FOUND_CATEGORY: "NOT_FOUND_CATEGORY",
		NOT_FOUND_ITEM: "NOT_FOUND_ITEM"
	},
	authentication: {
		NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
		EMAIL_OR_PASSWORD_INCORRECT: "EMAIL_OR_PASSWORD_INCORRECT",
		TOKEN_EXPIRED: "TOKEN_EXPIRED",
		TOKEN_GENERATED: "TOKEN_GENERATED",
		TOKEN_INVALID: "TOKEN_INVALID",
		PERMISSION_DENIED: "PERMISSION_DENIED"
	},
	created: {
		USER_CREATED: "USER_CREATED",
		CATEGORY_CREATED: "CATEGORY_CREATED",
		ITEM_CREATED: "ITEM_CREATED"
	},
	getting: {
		USER_SEARCHED: "USER_SEARCHED",
		CATEGORY_SEARCHED: "CATEGORY_SEARCHED",
		ITEM_SEARCHED: "ITEM_SEARCHED",
		USER_LIST_SEARCHED: "USER_LIST_SEARCHED",
		CATEGORY_LIST_SELECTED: "CATEGORY_LIST_SELECTED",
		ITEM_LIST_SELECTED: "ITEM_LIST_SELECTED"
	},
	deleted: {
		CATEGORY_DELETED: "CATEGORY_DELETED",
		ITEM_DELETED: "ITEM_DELETED"
	}
};